version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - '7500:7500'
    env_file:
      - .env
      - .env.db
    networks:
      - hr_docker_network

networks:
  hr_docker_network:
    external: true